### ISSUE TITLE
ESP compatibility

### ISSUE THREAD

**Issue by spike3312** [john30/ebusd-esp#1]
Hi,

I have a vailant boiler and am in the process of tryin to read various things like flow, return, target and room temperatures off the Ebus when i came across this.

I have extensively used ESP modules for various things such as temp sensors and temp/humidity sensors, mostly based on Arduino with my own code.

I was looking at your implementation but it doesn't say anything about how the data comes out of the ESP to something workable.

Matt

**Comment by john30** [comment]
This firmware is focusing on lowest possible latency when sending on the bus and is merely a TCP2serial or UDP2serial converter. In order to extract data from your boiler, you'd setup [ebusd](https://github.com/john30/ebusd) to use a Wemos with this firmware attached to a [hardware interface](https://github.com/john30/ebusd/wiki/6.-Hardware) with [recommendation on this one](https://forum.fhem.de/index.php/topic,75878.0.html)
