### ISSUE TITLE
Cant adquire Ebus signal

### ISSUE THREAD

**Issue by freddykat** [john30/ebusd-esp#26]
Hello,
First give a all thumbs up for the programmer that have done all this work.
Im trying to implement it on my "Saunier Duval Thelia Condens 30-A, that I know forefact that have Ebus and even the brand sells some expensive wifi thermostat to it.
That being said I bougth the adapter and open my boiler.
Im gona share what I've seen prior to connect it first time.
Ebus voltage is stable at 21.0 volts (thats weird) but yet flashed the wemos and im able to enter the HTML page of connection however I see this on the Weemos and make no sense to me.
Could be something going crazy on the boiler? Something on the adapter?
Have no ideia how to do now, since there is some other point on the pcb that is around 17v but still get this: 

Chip ID: 00513121
Hostname: ebus-513121
Up time: 4637
Free heap: 33024
ebusd connected: no
eBUS signal: no signal

see atachement

How should I test further? 

Thanks for your kind help

**Comment by john30** [comment]
are you sure that the device:
- has really an eBUS connection?
- is actually using it (instead of waiting for someone to drive the bus)?
There are devices that have an eBUS but in a rather passive mode, i.e. a SYN generator has to be available on the bus. ebusd supports this by using the "--generatesyn" option to ebusd. You might want to try it.
